plugins {
    id 'java'
}

group = 'org.scoula'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    //mySQL 드라이버
    implementation 'com.mysql:mysql-connector-j:8.0.33'

    //lombok library
    implementation 'org.projectlombok:lombok:1.18.42'
    compileOnly 'org.projectlombok:lombok:1.18.34'
    annotationProcessor 'org.projectlombok:lombok:1.18.34'

    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
    useJUnitPlatform()
}